### PR TITLE
display year in ftp list command

### PR DESCRIPTION
**Pull request by stuarthu**
Signed-off-by: Stuart Hu <hushijie@qiniu.com>

### CODE REVIEW

**Comment by bancek** [comment]
Thank you for your contribution. Could you also write some tests? Take a look at how tests for `STOR` command are implemented: https://github.com/koofr/graval/blob/master/graval_test.go#L1457

**Comment by stuarthu** [comment]
done

**Comment by stuarthu** [comment]
can some one help merge this pr?

**Comment by bancek** [comment]
I will merge this PR soon. I just need to check the FTP documentation for time display. And `AppendFile` needs to be optional (in separate interface and checked using type assertion) because some drivers might not support it.

**Pull request closed without merging**
